from . import sh_employee
from . import sh_job
from . import sh_department
from . import sh_calendar
from . import sh_employee_cat
from . import sh_compute
from . import sh_onchange
from . import sh_trip
from . import sh_action
from . import sh_task
from . import sh_test
from . import sh_doctor
from . import sh_patient
from . import sh_diagnosis
from . import sh_res_partner
from . import sh_product
from . import sh_account_tax
from . import sh_sale_order
from . import sh_sale_order_line
from . import sh_orm_create
from . import sh_orm_employee
from . import sh_orm_category
from . import sh_age_category
from . import sh_inheritance
from . import sh_note