from . import sh_allergy_type
from . import sh_allergy
from . import sh_medicine_form
from . import sh_medicine_ingredient
from . import sh_commission_type
from . import sh_specialization_category
from . import sh_pharmacy_doctor
from . import sh_pharmacy_patient
from . import sh_pharmacy_product
from . import sh_pharmacy_sale_order
from . import sh_pharmacy_vendor
from . import sh_doctor_commission
from . import sh_split_sale_order